//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AikoStudio
{
    using System;
    using System.Collections.Generic;

    public partial class Curriculum
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }
        public int GroupSubjectId { get; set; }
        public int TeacherId { get; set; }
        public decimal EducationalPractice { get; set; }
        public decimal PedagogicalPractice { get; set; }
        public decimal UndergraduatePractice { get; set; }
        public decimal IndustrialPractice { get; set; }
        public decimal ResearchPractice { get; set; }
        public decimal СommissionMembership { get; set; }
        public decimal SupervisoryWork { get; set; }
        public decimal TotalCredits { get; set; }
    
        public virtual GroupSubject GroupSubject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
