//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AikoStudio
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupOfStudents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupOfStudents()
        {
            this.Subject = new HashSet<Subject>();
        }
    
        public int Id { get; set; }
        public int SpecialtyId { get; set; }
        public int DepartmentId { get; set; }
        public int Contingent { get; set; }
        public int Year { get; set; }
        public int Semester { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Specialty Specialty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subject { get; set; }
    }
}
