//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AikoStudio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.GroupSubject = new HashSet<GroupSubject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int LectureQty { get; set; }
        public int SeminarQty { get; set; }
        public int LaboratoryQty { get; set; }
        public decimal LectureCreditQty { get; set; }
        public decimal SeminarCreditQty { get; set; }
        public decimal LaboratoryCreditQty { get; set; }
        public decimal OtherCreditQty { get; set; }
        public decimal AllCreditQty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupSubject> GroupSubject { get; set; }
    }
}
